name: Build and Run ChatGlmCodeReview By Main Maven Jar

on:
  push:
    branches:
      - '*' #代表推送任何分支都执行工作流
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Copy chatglm-code-review-sdk JAR
        run: mvn dependency:copy -Dartifact=com.rsl.middleware:chatglm-code-review-sdk:1.0 -DoutputDirectory=./libs

      - name: Run Code Review
        run: java -jar ./libs/chatglm-code-review-sdk-1.0.jar
